# Generated by Django 4.2.15 on 2024-08-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('UnitOfMeasure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necipes_name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.ingredients')),
                ('RecipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseDate', models.DateField()),
                ('Quantity', models.FloatField()),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('ExpiryDate', models.TimeField()),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.ingredients')),
            ],
        ),
    ]
