# Generated by Django 4.2.15 on 2024-08-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='ingredients_size',
            field=models.FloatField(null=True),
        ),
    ]
