# Generated by Django 4.2.15 on 2024-08-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_inventory_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='ExpiryDate',
            field=models.DateField(default='2026-12-25'),
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.ingredients')),
            ],
        ),
    ]
