# Generated by Django 4.2.15 on 2024-09-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_stock_user_alter_ingredients_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
