# Generated by Django 4.2.15 on 2025-01-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_recipes_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
