# Generated by Django 4.2.15 on 2025-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
